import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerated sidebar. Chapter filenames use numeric prefixes
// (01-, 02-, ...) which Docusaurus's number-prefix parser converts
// into sidebar positions automatically. The homepage (docs/index.md)
// sets sidebar_position: 0 explicitly.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
